name: winforms workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # step 1: setup the dotnet stuff
  setup:
    strategy:
      matrix:
        target-platform: [x64]
    runs-on: windows-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OUTPUT_FOLDER: /out
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

# step 2: publish the content
  publish:
    runs-on: windows-latest
    steps:
      - name: Build w/ dotnet
        run: dotnet build -c Release -o ${{env.OUTPUT_FOLDER}}

      - name: Publish w/ dotnet
        run: dotnet publish -c Release -o ${{env.OUTPUT_FOLDER}}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: 'test-tag-name'
          release_name: 'test-release-name'
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{env.OUTPUT_FOLDER}}
          asset_name: '*.*'
          asset_content_type: application/zip

      - name: Publish Release
        uses: eregon/publish-release@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}
