name: Build & Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # step 1: setup the dotnet stuff
  setup:
    runs-on: ubuntu-latest
    
    env:
      APP_PROJECT_PATH: ./src/Dashboard/Dashboard.csproj
      TEST_PROJECT_PATH: ./test/Dashboard/Dashboard.Tests.csproj
      ARTIFACT_PATH: ./out/
      SOLUTION_PATH: ./J-EmZee.sln
      
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    outputs:
      ARTIFACT_PATH: $env:ARTIFACT_PATH
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          # cache: true
        
      - name: Display dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore 
        
      - name: Build solution
        run: dotnet build $SOLUTION_PATH --no-restore

      - name: Run tests
        run: dotnet test $TEST_PROJECT_PATH --no-build --no-restore
      
      - name: Make output directory
        run: mkdir $ARTIFACT_PATH
        
      - name: Compile app as Release
        run: >-
          dotnet publish $APP_PROJECT_PATH
          -o $ARTIFACT_PATH
          -c Release
          -r win-x64
          --self-contained true
          -p:PublishSingleFile=true
          -p:IncludeNativeLibrariesForSelfExtract=true
      
      - name: 'DEBUG: Log output'
        run: ls $ARTIFACT_PATH

      - name: 'DEBUG: Log overall directory structure'
        run: ls

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ${{ env.ARTIFACT_PATH }}
          retention-days: 2

# step 2: publish the content
  publish:
    if: true == false
    needs:
      - setup
    runs-on: ubuntu-latest
    
    env:
      OUTPUT: ${{ needs.setup.outputs.ARTIFACT_PATH }}
    
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: 'test-tag-name'
          release_name: 'test-release-name'
          draft: true
          prerelease: true

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.OUTPUT }}
          asset_name: '*.*'
          asset_content_type: application/zip

      - name: Publish Release
        uses: eregon/publish-release@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}
