name: Build & Release

# Defines the trigger for when to execute this workflow.
on:
  # Arbitrary decisions that will likely be changed once a proper workflow is ready and branching strategy decided.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # step 1: build, test, and upload the artifact if successful.
  continuous-integration:
    # use the abstracted CI steps to build, test, compile, and upload artifacts.
    uses: ./.github/workflows/ci.yaml

  # step 2: publish the app as a release.
  continuous-deployment:
    # only trigger this if we're pushing onto master.
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
    
    # This job requires successful completion of the previous job.
    needs:
      - continuous-integration
    
    # use the abstracted CD steps to download artifacts, create a release, and publish it.
    uses: ./.github/workflows/cd.yaml
    
    # pass the inputs from the previous job.
    with:
      ARTIFACT_PATH: ${{ needs.continuous-integration.outputs.ARTIFACT_PATH }}
      ARTIFACT_NAME: ${{ needs.continuous-integration.outputs.ARTIFACT_NAME }}
      ARTIFACT_FILE: ${{ needs.continuous-integration.outputs.ARTIFACT_FILE }}
      # we may change this in the future.
      # ARTIFACT_TYPE: application/zip