name: winforms workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  do-things:
    strategy:
      matrix:
        target-platform: [x86, x64]
    runs-on: windows-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release
    
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: 'test-tag-name'
          release_name: 'test-release-name'
          draft: false
          prerelease: false
        
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{env.DOTNET_ROOT}}/myapp
          asset_name: '*.*'
          asset_content_type: application/zip

      - name: Publish Release
        uses: eregon/publish-release@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}